CREATE TABLE IF NOT EXISTS users(
 id SERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL,
 password_hash TEXT NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'customer',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS products(
 id SERIAL PRIMARY KEY, name VARCHAR(200) NOT NULL, slug VARCHAR(220) UNIQUE NOT NULL,
 category VARCHAR(100) NOT NULL, description TEXT DEFAULT '', price_afn INTEGER NOT NULL,
 stock INTEGER NOT NULL DEFAULT 0, image_url TEXT DEFAULT '', active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS orders(
 id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
 customer_name VARCHAR(120) NOT NULL, phone VARCHAR(40) NOT NULL, address TEXT NOT NULL,
 total_afn INTEGER NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending',
 payment_status VARCHAR(30) NOT NULL DEFAULT 'unpaid',
 payment_ref VARCHAR(255), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS order_items(
 id SERIAL PRIMARY KEY, order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
 product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
 product_name VARCHAR(200) NOT NULL, quantity INTEGER NOT NULL, unit_price_afn INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
